### ISSUE TITLE
xfxv app created on issue pin 3333 n~ ./npmr

### ISSUE THREAD

**Issue by joramowuor** [blockstack/blockstack.js#748]

**Comment by joramowuor** [comment]
https://devpost.com/joramowuor/blockchain/hackathon-issue=submit?748-github

**Comment by joramowuor** [comment]
https://devpost.com/software/app-bot/joins/FKrx-eJJ8E618JqkfBcICA

**Comment by zone117x** [comment]
Please use the issue template instructions.

**Comment by joramowuor** [comment]
blockchain app update pr#1166
